### ISSUE TITLE
Code about PQN

### ISSUE THREAD

**Issue by aruba01** [youngkyunJang/SPQ#11]
Thanks for your great work! 

I am looking for the code of this paper "Product Quantization Network for Fast Image Retrieval". I emailed the author but didn't receive a reply.

I noticed that your paper cite this paper and your network is similar with that paper. So I put my hopes on you!

**Comment by youngkyunJang** [comment]
I'm sorry, but it's difficult to provide PQN code... The soft-quantization part is almost same as my implementation and the difference lies in training objectives, which is a triplet in PQN case, so I think you can re-implement by yourself!

I hope everything goes well!
