### ISSUE TITLE
I want to know about the division of the data set. 

### ISSUE THREAD

**Issue by yayaYsmileT** [youngkyunJang/SPQ#12]
How to achieve the division of CIFAR10 dataset for training and get the effect in the paper? 
We look forward to hearing from you.

**Comment by youngkyunJang** [comment]
Hi,

I just divide the training / test set as the official dataset configuration

https://www.cs.toronto.edu/~kriz/cifar.html

Please refer to the link :)

**Comment by yayaYsmile** [comment]
Thank you for your reply. My problem is that the output mAP and MAX mAP are 0 when using CIFAR10 data set.I don't know what went wrong
