### ISSUE TITLE
How to realize the retrieval function

### ISSUE THREAD

**Issue by 834799106** [youngkyunJang/SPQ#3]
I'm sorry to disturb you. At present, I have realized the training of the model. Now I want to use the model to realize the retrieval effect instead of simply calculating MAP, that is, input some images and return the index of topk images.I have no idea at present and hope to get your help

**Comment by youngkyunJang** [comment]
Hello, please refer to Retrieval.py line 40, (inside of the def Evaluate_mAP), 
You can get indices of retrieval results with T.argsort(pqDist_one(C, N_books, gallery_codes, query_codes[i])),
I hope it will solve your problem!
