### ISSUE TITLE
Still can not reproduce results

### ISSUE THREAD

**Issue by xiaosu-zhu** [youngkyunJang/SPQ#7]
Hi @youngkyunJang , I've face the similar issue as in #6 . At first, I took the following packages as my environment:

```
PyTorch: 1.10.1
torchvision: 0.11.2
kornia: 0.6.2
```

And I got `mAP = 0.7673` at `2800` epochs. Then, I downgrade to following versions that exactly match your suggestions in [README.md](https://github.com/youngkyunJang/SPQ#install-requirements-on-your-environment):

```
PyTorch: 1.7.1
torchvision: 0.8.2
kornia: 0.5.10
```

But Still have `mAP = 0.7842` at `3800` epochs. There's still a gap with original paper. Do you have any idea?

**Comment by youngkyunJang** [comment]
Hello, can you compute mAP scores more often after 2500 epochs? It will show some different results!

**Comment by xiaosu-zhu** [comment]
> Hello, can you compute mAP scores more often after 2500 epochs? It will show some different results!

Hi Younkyun, I've already run for more than `2500` epochs, please check the detail issue:

> Hi @youngkyunJang , I've face the similar issue as in #6 . At first, I took the following packages as my environment:
> 
> ```
> PyTorch: 1.10.1
> torchvision: 0.11.2
> kornia: 0.6.2
> ```
> 
> And I got `mAP = 0.7673` at `2800` epochs. Then, I downgrade to following versions that exactly match your suggestions in [README.md](https://github.com/youngkyunJang/SPQ#install-requirements-on-your-environment):
> 
> ```
> PyTorch: 1.7.1
> torchvision: 0.8.2
> kornia: 0.5.10
> ```
> 
> But Still have `mAP = 0.7842` at `3800` epochs. There's still a gap with original paper. Do you have any idea?


I've also tried multiple runs, still can't achieve `>0.79` results...

**Comment by youngkyunJang** [comment]
Hello, I mean increase the evaluation frequency, after 2500 epochs. It will be better to obtain optimized results if you evaluate more often :)

**Comment by xiaosu-zhu** [comment]
Oh sorry I misunderstood you. I will give a try.

**Comment by Rong-Zou** [comment]
> Oh sorry I misunderstood you. I will give a try.

Hi, were you able to reproduce the results?
